version: "3.8"

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=YourStrong@Passw0rd
      # - PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
      - MSSQL_RPC_PORT=135
      - CONFIG_EDGE_BUILD=
      - MSSQL_PID=developer
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql # Mount initialization script


  # sqlmigration:
  #   build:
  #     context: ./sqlmigration
  #     dockerfile: Dockerfile
  #   depends_on:
  #     - sqlserver

  # dotnetapp:
  #   build:
  #     context: ./server
  #     dockerfile: Dockerfile
  #   ports:
  #     - "7189:80"
  #   depends_on:
  #     - sqlserver

  # reactapp:
  #   build:
  #     context: ./client
  #     dockerfile: Dockerfile
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - dotnetapp
